### ISSUE TITLE
Add-IPReservation

### ISSUE THREAD

**Issue by kentuckyvmdude** [EvotecIT/PowerInfoblox#1]
This is a feature request, not an Issue. Apologies if this is the wrong place to ask, but I'm not real familiar with Github. We use our Infoblox for our servers more as simple documentation, so don't use fixed addresses tied to MAC's and just use IP reservations with descriptions.

Any chance this could be added? Add-IPReservation or something like that.

I might look into doing it myself if I can find some time, but I don't have any experience with the Infoblox API and very little experience with API's in general, so I figured I'd just ask.

**Comment by PrzemyslawKlys** [comment]
I'm not an expert on infoblox so I need some help:
- https://insights.infoblox.com/resources-deployment-guides/infoblox-deployment-infoblox-rest-api -> here's the API link

Which action would be the IP reservation if not for mac address match?

**Comment by kentuckyvmdude** [comment]
So its not a separate command, it's just a change in the match_client parameter for fixedaddress : DHCP Fixed Address object.

(found at https://myinfoblox.local/wapidoc/)

> match_client
> 
> The match_client value for this fixed address. Valid values are:
> “MAC_ADDRESS”: The fixed IP address is leased to the matching MAC address.
> “CLIENT_ID”: The fixed IP address is leased to the matching DHCP client identifier.
> 
> **“RESERVED”: The fixed IP address is reserved for later use with a MAC address that only has zeros.**
> 
> “CIRCUIT_ID”: The fixed IP address is leased to the DHCP client with a matching circuit ID. Note that the “agent_circuit_id” field must be set in this case.
> “REMOTE_ID”: The fixed IP address is leased to the DHCP client with a matching remote ID. Note that the “agent_remote_id” field must be set in this case.
> 
> Type
> String.
> 
> Valid values are:
> CIRCUIT_ID
> CLIENT_ID
> MAC_ADDRESS
> REMOTE_ID
> RESERVED
> 
> Create
> The default value is MAC_ADDRESS.
> 
> Search
> The field is available for search via
> ‘=’ (exact equality)

So you wouldn't even need an Add-IPReservation if its possible to add an optional parameter to Add-InfobloxFixedAddress, although the GUI of infoblox treats them as two separate items, so it might be more dummy proof to have an entirely separate command. Add-InfobloxReservation. I'll leave that decision in your more than capable hands.

**Comment by PrzemyslawKlys** [comment]
![image](https://github.com/EvotecIT/PowerInfoblox/assets/15063294/62ce8bc1-f279-4980-9287-28b9e12aa152)

The current api we call is this. What's the API call wapidoc shows that needs to be called?

**Comment by kentuckyvmdude** [comment]
![image](https://github.com/EvotecIT/PowerInfoblox/assets/19632196/d468299d-ad9f-45f0-92f4-b95a59354ff6)

Right under that section. Looks like it just sets the mac to all zeroes and calls it done. 

The WAPIDOCs treat **_match_client_** as a field just like **_ipv4addr_** and **_mac_** so I'm guessing 

```
    $invokeInfobloxQuerySplat = @{
        RelativeUri    = 'fixedaddress'
        Method         = 'POST'
        QueryParameter = @{
            ipv4addr = $IPv4Address
            mac      = $MacAddress.ToLower()
            match_client = RESERVED
        }
    }
```

Would also do the job.

**Comment by kentuckyvmdude** [comment]
I'll try it out and see what happens

**Comment by PrzemyslawKlys** [comment]
So first case you just provide an mac address 00:00 etc to existing function and I should work, or we need to add new thingy,  I guess adding optional parameter which sets match_client to one of the values `Valid values are:
CIRCUIT_ID
CLIENT_ID
MAC_ADDRESS
REMOTE_ID
RESERVED` if present would not be that hard.

**Comment by kentuckyvmdude** [comment]
Nah, just setting the mac to 00's is easy and you could add it to your help file. Adding all those extra parameters just means adding even more fields, there's no telling what else REMOTE_ID needs to work correctly for example.

I was going to test out the all 0's method for the mac as well as just permanently setting match_field to RESERVED, but turns out I don't have API access to our Infoblox grid, so I'm going to have to reach out to the admin and pray he doesn't just tell me to buzz off. I appreciate you helping me work through this. Your choice whether to add some RESERVATION verbage to the help. I might be the only one that ever needs it.
